include:
  - template: Jobs/Dependency-Scanning.latest.gitlab-ci.yml
  - template: Jobs/SAST.latest.gitlab-ci.yml
  - template: Jobs/Secret-Detection.latest.gitlab-ci.yml

# Always run GitLab security in amd64 Docker runner
.security:
  needs: []
  tags:
    - docker
    - amd64

# Dependency scanning
dependency_scanning:
  extends:
    - .security
    - .go

  # noinspection YAMLSchemaValidation
  before_script:
    - !reference [.go, before_script]

# Override gemnasium-dependency_scanning image
gemnasium-dependency_scanning:
  image: registry.mreg.io/danny900714/gemnasium:latest

# SAST
sast:
  extends:
    - .security
    - .go
  variables:
    GITLAB_ADVANCED_SAST_ENABLED: "true"

# Secret detection
secret_detection:
  extends:
    - .secret-analyzer  # GitLab's secret_detection extends
    - .security
