include:
  - template: Jobs/Dependency-Scanning.latest.gitlab-ci.yml
  - template: Jobs/SAST.latest.gitlab-ci.yml
  - template: Jobs/Secret-Detection.latest.gitlab-ci.yml
  - template: Jobs/Container-Scanning.latest.gitlab-ci.yml

# Always run GitLab security in amd64 Docker runner
.security:
  needs: []
  tags:
    - docker
    - amd64

.dep:
  extends: .go
  before_script:
    - !reference [.go, before_script]
    - !reference [.node, before_script]

# Dependency scanning
dependency_scanning:
  extends:
    - .security
    - .dep

  # noinspection YAMLSchemaValidation
  before_script:
    - !reference [.dep, before_script]

# SAST
sast:
  extends:
    - .security
    - .dep
  variables:
    GITLAB_ADVANCED_SAST_ENABLED: "true"

# Secret detection
secret_detection:
  extends:
    - .secret-analyzer  # GitLab's secret_detection extends
    - .security

# Container scanning
container_scanning:
  extends:
    - .container_scanning
    - .security
  parallel:
    matrix:
      - COMPONENT: ["api", "web"]
  needs:
    - api:docker
    - web:docker
  variables:
    GIT_STRATEGY: fetch
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/$COMPONENT
    CI_APPLICATION_TAG: $CI_COMMIT_SHORT_SHA
    CS_DOCKERFILE_PATH: $COMPONENT/Dockerfile
