.flyway:
  extends: .db
  stage: test
  tags:
    - docker
    - amd64
  image:
    name: redgate/flyway:10-alpine
    entrypoint: [""]
  variables:
    flyway_environment: ci
    FLYWAY_SCHEMAS: commit_$CI_COMMIT_SHORT_SHA
  before_script:
    - cd migrations

flyway:migrate:
  extends: .flyway
  needs: []
  script:
    - flyway info migrate validate
  artifacts:
    name: report.html
    paths:
      - migrations/report.html
    expose_as: Flyway Info

flyway:clean:
  extends: .flyway
  needs:
    - job: flyway:migrate
    - job: api:test
      optional: true
  rules:
    - when: always
  script:
    - flyway clean
