.web:
  image: node:latest
  before_script:
    # pnpm config
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir web/.pnpm-store
    - cd web
    - pnpm install
  cache:
    key:
      files:
        - web/pnpm-lock.yaml
    paths:
      - web/.pnpm-store
    policy: pull

web:dep:
  extends: .web
  stage: .pre
  script:
    - pnpm install
  cache:
    policy: pull-push

web:build:
  extends: .web
  stage: build
  needs: [web:dep]
  script:
    - pnpm build

web:lint:
  extends: .web
  stage: test
  needs: [web:dep]
  script:
    - pnpm lint

web:format:
  extends: .web
  stage: test
  needs: [web:dep]
  script:
    - pnpm format:ci
